### ISSUE TITLE
warp_image function runs very slow 

### ISSUE THREAD

**Issue by lxtGH** [vt-vl-lab/pytorch_flownet2#3]
Hi ! Thanks for your code , It seems that warp_image in flowlib.py run very slow. I wonder if exits other methods to speed it up

**Comment by Yuliang-Zou** [comment]
Because that's numpy code, only for visualization, not training. You can check [this line](https://github.com/vt-vl-lab/pytorch_flownet2/blob/master/FlowNet2_src/models/flownet2.py#L80)

**Comment by lxtGH** [comment]
Thanks for your reply, I see. I am not understand the wrap process, can you give me some link for study? In pytorch forum, I find people use **grid_sample** function to implement image warp , what is difference between your code and that function?

**Comment by JiamingSuen** [comment]
@lxtGH Would you please share the link of `grid_sample` implementation for flow warping! Thanks a lot!

**Comment by Yuliang-Zou** [comment]
@JiamingSuen Check this: http://pytorch.org/docs/0.3.1/nn.html#grid-sample

**Comment by Yuliang-Zou** [comment]
@lxtGH I did not write the code, I just re-arrange it into easy-to-use package. Seems that when this code was released, pytorch has no grid_sample module yet.

**Comment by JiamingSuen** [comment]
@Yuliang-Zou Thanks for the reference! 
In fact, I'm having trouble writing a flow warping function with `grid_sample`. Since `grid_sample` is originally used for STN, I didn't find a straightforward way to generate grid with flow that outputted by the network. Actually I only to make sure what proposed in [this thread](https://discuss.pytorch.org/t/how-to-use-the-grid-sample-to-warp-the-image/12443) is correct. It would be nice if you can provide some information. Thanks!

**Comment by Yuliang-Zou** [comment]
@JiamingSuen My understanding (not necessarily correct):
1. You compute the flow
2. You can know the correspondence from (x,y) in Im1 to (x',y') in Im2
3. Normalize the coordinates (x',y') to [-1, 1], you get `grid`
4. `x` should be Im2, if you are doing inverse warp

**Comment by lxtGH** [comment]
Hi, Thanks for your reply 
I ask the same question in this [issue](https://github.com/hellock/cvbase/issues/4)
but I think the **last line** of the code should be the **input** **x**, Is my understanding correct?
@Yuliang-Zou @JiamingSuen
