### ISSUE TITLE
Spatial Size Constraint

### ISSUE THREAD

**Issue by inkawhich** [vt-vl-lab/pytorch_flownet2#8]
Why does the spatial size have to be a multiple of 64?

**Comment by Yuliang-Zou** [comment]
Hi @inkawhich , because we have 6x down sampling and skip connection for each of the scale. If the size is not a multiple of 64, you will need to resize or crop the feature in the intermediate layers. You can also try this, but the typical thing people do is to resize the image size to be a multiple of 64.
